FROM osm_ui_base:v1
LABEL maintainer="yangshuo@si-tech.com.cn"

RUN cp -r /osm_ui/node_modules /tmp
RUN rm -rf /osm_ui/*
COPY . /osm_ui
RUN cp -r /tmp/node_modules /osm_ui

RUN npm run build && cp -r /osm_ui/dist /etc/nginx
CMD ["/usr/sbin/nginx","-c","/etc/nginx/nginx.conf"]

EXPOSE 80
